[package]
name = "resvg_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "resvg_python"
crate-type = ["cdylib"]


[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }
resvg = { version = "0.42.0", default-features = false }
tiny-skia = "0.11.4"
usvg = "0.42.0"
